import RootProvider from '@/providers/RootProvider';
import type { Metadata } from 'next';
import { Roboto } from 'next/font/google';
import 'react-toastify/dist/ReactToastify.css';
import '../styles/globals.css';

const roboto = Roboto({ subsets: ['latin'], weight: '400' });

export const metadata: Metadata = {
  title: 'Integração com TOTVS RM',
  description: 'Generated by Peixola',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body
        className={`${roboto.className} antialiasing flex flex-col min-h-full min-w-full`}
      >
        <RootProvider>{children}</RootProvider>
      </body>
    </html>
  );
}
