import RootProvider from '@/providers/RootProvider';
import type { Metadata } from 'next';
import { Montserrat } from 'next/font/google';
import 'react-toastify/dist/ReactToastify.css';
import '../styles/globals.css';

const monteserrat = Montserrat({ subsets: ['latin'], weight: '400' });

export const metadata: Metadata = {
  title: 'Integração com TOTVS RM',
  description: 'Generated by Peixola',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br" suppressHydrationWarning>
      <body
        className={`${monteserrat.className} antialiasing flex flex-col min-h-full min-w-full`}
      >
        <RootProvider>{children}</RootProvider>
      </body>
    </html>
  );
}
