services:
  nginx:
    image: nginx:latest
    container_name: totvs-nginx
    ports:
      - '3330:3330'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - totvs-app
    networks:
      - totvs-network

  totvs-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: totvs-app
    restart: always
    ports:
      - '3333:3333'

    volumes:
      - .:/app
      - /app/node_modules

    environment:
      POSTGRES_HOST: totvs-backend
      POSTGRES_PORT: 5432
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: totvs
      POSTGRES_DATABASE: totvs
      NODE_ENV: development
    depends_on:
      - totvs-backend

    command: yarn dev

    networks:
      - totvs-network

  totvs-backend:
    image: postgres:latest
    command: [ 'postgres', '-c', 'log_statement=all' ]
    container_name: totvs-backend
    restart: always
    healthcheck:
      test: [ 'CMD', 'pg_isready', '-U', 'postgres', '-d', 'postgres' ]
      interval: 5s
      retries: 10

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: totvs
      POSTGRES_DB: totvs

    ports:
      - '5432:5432'

    volumes:
      - ./initdb:/docker-entrypoint-initdb.d

    networks:
      - totvs-network

networks:
  totvs-network:
    driver: bridge
